### ISSUE TITLE
Hash Mining x2

### ISSUE THREAD

**Issue by CookedPages** [DexterHuang/CyberCodeOnline#838] opened 2021-05-29 14:56 UTC
Now after mining 1 hash at a time several times, now whenever I select 1 hash I end up doing 2 automatically (30 min instead of 15). I am afraid to try selecting 2 on the basis that it could make me do 4 at a time depending on how the bug goes.

**Comment by DexterHuang** [comment] 2021-06-01 07:57
I was not able to reproduce this, can you make confirm if it happens? I will close this first

**Closed by DexterHuang** 2021-06-01 07:57 UTC
