### ISSUE TITLE
Draining battery on mobile

### ISSUE THREAD

**Issue by Misaki290** [DexterHuang/CyberCodeOnline#477] opened 2021-04-09 22:43 UTC
Hi! I think that this should be solved as soon as possible. The game basically drains my 100% battery (3000 mAh) in probably 1 hour or less.
At this rate I don't even feel like using the app anymore. I just use it sparingly.
If it matters 'Performance score' is 2430 or something like that.
It's still very soliciting. I think that it does that because the app isn't very optimized.
Of course, I am not an expert.
Just my thoughts.

**Comment by tripplehelix** [comment] 2021-04-10 12:36
I have added this to the bug tracker as high priority

**Comment by DexterHuang** [comment] 2021-04-11 10:33
@Misaki290  performance score is lower the better 2430 is very bad I think 0.0
can I know your phone model and do you have a specific page or tab that is especially laggy?

does the app drain battery even closed?

**Comment by Misaki290** [comment] 2021-04-11 10:38
Huawei P9 Lite (2018)
It doesn't lag or anything like that and it doesn't drain battery when closed.
When open it heats up and the battery goes down pretty fast.

**Comment by DexterHuang** [comment] 2021-04-11 11:05
Is there a specific page or tab or location that make it heat up? Or every page?

**Comment by Misaki290** [comment] 2021-04-11 11:39
> Is there a specific page or tab or location that make it heat up? Or every page?

Every page.

**Comment by Misaki290** [comment] 2021-04-16 14:37
Performance is now, around 3200. 
I know that you tried to improve it.
I just think that may my phone is really bad.
Potato phone.

**Comment by DexterHuang** [comment] 2021-04-17 10:38
Hmmm I have dispatched a few optimaztion updates, hopefully it does help you with the battery issue @@

**Comment by tripplehelix** [comment] 2021-04-17 17:58
@Misaki290 let us know if the issue has been resolved so we can close this issue.

**Comment by Misaki290** [comment] 2021-04-17 18:03
Well, my PS is still around 2100 but I can't tell anyone if it's the app or just my phone.
I'll close the issue.

**Comment by JEricaM** [comment] 2021-04-19 13:58
I have the same problem too. Cybercode app in background drains my battery in a hour or less too. 
performance score 1947

**Comment by Misaki290** [comment] 2021-04-19 14:01
Since I am not the only person anymore who is complaining about this, I have re-opened the issue.

**Comment by DexterHuang** [comment] 2021-04-19 15:39
🤔🤔 This is weird, there is no any clue? Like is there some place that is specially laggy?

**Comment by JEricaM** [comment] 2021-04-19 16:38
@DexterHuang nothing laggy. today I did only afk jobs (and most of the days) using the app in background. I will try to look for more details.

**Comment by Misaki290** [comment] 2021-04-20 11:45
> 🤔🤔 This is weird, there is no any clue? Like is there some place that is specially laggy?

I noticed that dungeons are really laggy.

**Comment by JEricaM** [comment] 2021-04-20 13:48
For me dungeons are laggy a little bit too but I do max one dungeon a day so is not the cause of the battery drain I think.
I can confirm that the problem it's the app in background. My device tell me that it's consuming too much battery (more than Whatsapp) and I did only afk tasks. The battery today went from 100% to 37% in 6 hours more o less.

**Comment by Misaki290** [comment] 2021-04-20 13:53
> For me dungeons are laggy a little bit too but I do max one dungeon a day so is not the cause of the battery drain I think.
> I can confirm that the problem it's the app in background. My device tell me that it's consuming too much battery (more than Whatsapp) and I did only afk tasks. The battery today went from 100% to 37% in 6 hours more o less and I'm not using it beside cybercode afk tasks

In 6 hours??? What's even your battery capacity? 
How long does it lasts normally?
Mine's is 3000 mAh.
I would consider myself lucky if the battery would last 6 hours without recharing even with the app in the background. Just saying.

**Comment by DexterHuang** [comment] 2021-04-20 14:12
hmmm I will be a focus on optimization first 
seems like there needs to be a lot of optimization haha

**Comment by Misaki290** [comment] 2021-04-20 14:18
> hmmm I will be a focus on optimization first
> seems like there needs to be a lot of optimization haha

Yep.

**Comment by JEricaM** [comment] 2021-04-20 14:20
@Misaki290 
My battery it's 3550 mAh
Without Cybercode in background I charge it only once a day but in the evening, not after lunch xD

**Comment by Misaki290** [comment] 2021-04-20 14:23
@JEricaM
Mine last 3 hrs and I recharge it like 3 or 4 times a day. Yeah I also use phone constantly.
Don't have much to do anyway. 😞

**Comment by DexterHuang** [comment] 2021-04-20 14:24
Hm does your battery drain quickly with any game or its only my game is eating it fast? @@

**Comment by Misaki290** [comment] 2021-04-20 14:29
@DexterHuang
Your game seems to be the most demanding.
Other games  that I play don't drain as much.

**Comment by DexterHuang** [comment] 2021-04-21 11:48
hello, I have pushed a update just now, could you guys help see if there is any improvement ?

**Comment by JEricaM** [comment] 2021-04-25 21:36
I will try to understand if I see improvements :)

**Comment by tripplehelix** [comment] 2021-04-26 12:55
@Misaki290 @JEricaM Has this issue been solved?

**Comment by JEricaM** [comment] 2021-04-26 14:24
Just done a test:

03:13 PM -> battery level 78% 
started a scavenge afk task
04:22 PM - > battery level 74%

It's impossible to do better than this xD

**Comment by Misaki290** [comment] 2021-04-26 14:58
> @Misaki290 @JEricaM Has this issue been solved?

![IMG_20210426_174806](https://user-images.githubusercontent.com/79731146/116102797-ab69dd80-a6b7-11eb-80eb-912237101779.png)
This was my message for you 3 days ago.
There's no more lag in dungeons and inside dungeons performance score dropped to 2800 from 3400 or so.
I guess that part of the problem could also be that my battery is 2 years old and it has a drain faster than ussually.
Phone still heats a bit but not as much as it used to be.
Maybe future tweaks can still be done but I really don't want to push it on you than I already did.

**Comment by tripplehelix** [comment] 2021-04-26 15:16
Don't use the performance score as a comparison, use your own judgement.

**Closed by tripplehelix** 2021-04-26 15:16 UTC
Labels: bug
