### ISSUE TITLE
Various crafting levels (Printing, Med Science) higher than actual player level.

### ISSUE THREAD

**Issue by Skullbuns** [DexterHuang/CyberCodeOnline#806] opened 2021-05-20 15:37 UTC
Hello, is every other level is supposed to be auto-capped by your player level? _(E.g if you were level 42 you would max out at printing rank 42 until you leveled up)_

If this is the case then there seems to be a bug that causes crafting levels to be higher than the actual player level. My account has managed to achieve printing rank 14 and medical science 14 whilst I am still at level 13? I have checked both the mobile app (android) and desktop version, both are the same.

This could be intentional, but I decided to report it in case it is a genuine bug.

Screenshots:

![wheewhoo](https://user-images.githubusercontent.com/84450038/119007927-97995a80-b989-11eb-8d6d-2129488c41c3.PNG)

![Screenshot_20210520-163125_CyberCode Online (2)](https://user-images.githubusercontent.com/84450038/119007946-9b2ce180-b989-11eb-98e3-7fcf8ebbd6c6.jpg)

**Comment by Misaki290** [comment] 2021-05-20 15:52
Every other skills should be capped at your player level. This is probably a bug.
This shows even after you restarted/reloaded the app/page?

**Comment by Skullbuns** [comment] 2021-05-20 15:54
Yep! I have refreshed many times over the day, still appearing.

**Comment by DexterHuang** [comment] 2021-05-20 16:01
I think this could be caused by the recent exp buff, I think there won't be any problems 🤔 harmless side effect I hope, let me just close it, feel free to reopen if this cause any issue

**Closed by DexterHuang** 2021-05-20 16:01 UTC
